# Generated by Django 3.2.5 on 2022-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220612_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
