# Generated by Django 3.2.5 on 2022-06-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rides_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='user',
            new_name='client',
        ),
    ]
