# Generated by Django 3.2.5 on 2022-06-17 12:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2547000000000', max_length=15, region=None),
        ),
    ]
