# Generated by Django 3.2.5 on 2022-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
