# Generated by Django 3.2.5 on 2022-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220623_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='ride',
        ),
        migrations.AddField(
            model_name='transactions',
            name='rideid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
