# Generated by Django 3.2.5 on 2022-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220623_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='rideid',
            field=models.CharField(max_length=100),
        ),
    ]
